leftnav:
- identifier: 10fd333d-f858-366b-6c63-b1c8bf2fbed5
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 6be13a02-adeb-e9d9-7e23-80a7c8ea9690
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: d3d06a6b-f750-ce44-7577-61b4afc478c2
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: c93fdb03-6063-b169-a61d-03b8da93c5ff
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: f2d20bc6-e990-0162-c262-60cd693b0cfb
  name: Readings
  pageRef: /pages/readings
  weight: 50
- identifier: 839264ac-7eac-f47f-059d-946bc1456b8c
  name: Related Resources
  pageRef: /pages/related-resources
  weight: 60
